import { LogoTemplate } from './types';

export const LOGO_TEMPLATES: LogoTemplate[] = [
  {
    id: 'wine-bar-elegant',
    name: 'Wine Bar Elegante',
    category: 'wine-bar',
    preview: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=200&fit=crop',
    tags: ['wine', 'elegant', 'restaurant'],
    canvasSize: { width: 400, height: 200 },
    elements: [
      {
        id: 'title-1',
        type: 'text',
        content: 'OSTERIA',
        x: 50,
        y: 60,
        width: 300,
        height: 50,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Playfair Display',
        fontSize: 42,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#2a1a1d',
        letterSpacing: 2,
        lineHeight: 1.2,
        textDecoration: 'none',
        opacity: 1
      },
      {
        id: 'subtitle-1',
        type: 'text',
        content: 'del borgo',
        x: 50,
        y: 110,
        width: 300,
        height: 25,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#6b3a2e',
        letterSpacing: 4,
        lineHeight: 1.2,
        textDecoration: 'none',
        opacity: 0.8
      },
      {
        id: 'decoration-1',
        type: 'shape',
        shape: 'rectangle',
        x: 150,
        y: 140,
        width: 100,
        height: 2,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: '#d9b99b',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 1,
        borderRadius: 1
      }
    ]
  },
  {
    id: 'modern-minimal',
    name: 'Moderno Minimale',
    category: 'modern',
    preview: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=300&h=200&fit=crop',
    tags: ['modern', 'minimal', 'clean'],
    canvasSize: { width: 300, height: 100 },
    elements: [
      {
        id: 'title-2',
        type: 'text',
        content: 'RESTAURANT',
        x: 20,
        y: 30,
        width: 260,
        height: 40,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Montserrat',
        fontSize: 32,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#2C3E50',
        letterSpacing: 1,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      {
        id: 'circle-1',
        type: 'shape',
        shape: 'circle',
        x: 250,
        y: 35,
        width: 30,
        height: 30,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: '#E74C3C',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 1
      }
    ]
  },
  {
    id: 'vintage-badge',
    name: 'Badge Vintage',
    category: 'vintage',
    preview: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=300&h=200&fit=crop',
    tags: ['vintage', 'badge', 'classic'],
    canvasSize: { width: 200, height: 200 },
    elements: [
      {
        id: 'badge-bg',
        type: 'shape',
        shape: 'circle',
        x: 25,
        y: 25,
        width: 150,
        height: 150,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: 'none',
        stroke: '#8B4513',
        strokeWidth: 3,
        opacity: 1
      },
      {
        id: 'vintage-title',
        type: 'text',
        content: 'BISTROT',
        x: 50,
        y: 80,
        width: 100,
        height: 25,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Merriweather',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B4513',
        letterSpacing: 1,
        lineHeight: 1.2,
        textDecoration: 'none',
        opacity: 1
      },
      {
        id: 'vintage-year',
        type: 'text',
        content: '1962',
        x: 75,
        y: 110,
        width: 50,
        height: 20,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B4513',
        letterSpacing: 2,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.8
      }
    ]
  },
  {
    id: 'script-elegant',
    name: 'Script Elegante',
    category: 'elegant',
    preview: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=300&h=200&fit=crop',
    tags: ['script', 'elegant', 'handwritten'],
    canvasSize: { width: 350, height: 120 },
    elements: [
      {
        id: 'script-main',
        type: 'text',
        content: 'Bella Vita',
        x: 50,
        y: 40,
        width: 250,
        height: 60,
        rotation: -3,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Dancing Script',
        fontSize: 48,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#C0392B',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      {
        id: 'script-sub',
        type: 'text',
        content: 'Ristorante',
        x: 120,
        y: 85,
        width: 110,
        height: 20,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'light',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#2C3E50',
        letterSpacing: 3,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.9
      }
    ]
  },
  {
    id: 'geometric-modern',
    name: 'Geometrico Moderno',
    category: 'modern',
    preview: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=300&h=200&fit=crop',
    tags: ['geometric', 'modern', 'shapes'],
    canvasSize: { width: 250, height: 100 },
    elements: [
      {
        id: 'geo-square',
        type: 'shape',
        shape: 'rectangle',
        x: 20,
        y: 30,
        width: 40,
        height: 40,
        rotation: 45,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: '#3498DB',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 1,
        borderRadius: 0
      },
      {
        id: 'geo-text',
        type: 'text',
        content: 'FUSION',
        x: 80,
        y: 35,
        width: 150,
        height: 30,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'Poppins',
        fontSize: 28,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#2C3E50',
        letterSpacing: 2,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      }
    ]
  }
];

export const getTemplatesByCategory = (category: string) => 
  LOGO_TEMPLATES.filter(template => template.category === category);

export const getTemplateById = (id: string) => 
  LOGO_TEMPLATES.find(template => template.id === id);