import { LogoTemplate } from './types';

// Template avanzati per ristoranti, wine bar e locali
export const ADVANCED_LOGO_TEMPLATES: LogoTemplate[] = [
  {
    id: 'wine-bar-luxe',
    name: 'Wine Bar di Lusso',
    category: 'wine-bar',
    preview: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop',
    tags: ['wine', 'luxury', 'elegant', 'script'],
    canvasSize: { width: 500, height: 300 },
    elements: [
      // Background decorativo
      {
        id: 'bg-decoration',
        type: 'shape',
        shape: 'rectangle',
        x: 0,
        y: 120,
        width: 500,
        height: 60,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: 'linear-gradient(135deg, #8B1538 0%, #C41E3A 50%, #8B1538 100%)',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.15,
        borderRadius: 0
      },
      // Titolo principale con font elegante
      {
        id: 'main-title',
        type: 'text',
        content: 'CHÂTEAU ROSSO',
        x: 50,
        y: 80,
        width: 400,
        height: 60,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Playfair Display',
        fontSize: 36,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#2C1810',
        letterSpacing: 3,
        lineHeight: 1.2,
        textDecoration: 'none',
        opacity: 1
      },
      // Sottotitolo con stile script
      {
        id: 'subtitle',
        type: 'text',
        content: 'Wine Bar & Bistrot',
        x: 100,
        y: 140,
        width: 300,
        height: 30,
        rotation: -2,
        zIndex: 3,
        locked: false,
        selected: false,
        fontFamily: 'Dancing Script',
        fontSize: 24,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B1538',
        letterSpacing: 1,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Decorazione sinistra
      {
        id: 'decoration-left',
        type: 'shape',
        shape: 'rectangle',
        x: 120,
        y: 185,
        width: 80,
        height: 2,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: '#DAA520',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.8,
        borderRadius: 1
      },
      // Decorazione destra
      {
        id: 'decoration-right',
        type: 'shape',
        shape: 'rectangle',
        x: 300,
        y: 185,
        width: 80,
        height: 2,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: '#DAA520',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.8,
        borderRadius: 1
      },
      // Anno di fondazione
      {
        id: 'year',
        type: 'text',
        content: 'EST. 1952',
        x: 200,
        y: 200,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B4513',
        letterSpacing: 2,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.9
      }
    ]
  },
  
  {
    id: 'trattoria-vintage',
    name: 'Trattoria Vintage',
    category: 'restaurant',
    preview: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop',
    tags: ['vintage', 'italian', 'rustic', 'classic'],
    canvasSize: { width: 400, height: 250 },
    elements: [
      // Bordo vintage circolare
      {
        id: 'vintage-border-outer',
        type: 'shape',
        shape: 'circle',
        x: 50,
        y: 25,
        width: 300,
        height: 200,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: 'none',
        stroke: '#8B4513',
        strokeWidth: 4,
        opacity: 1
      },
      // Bordo interno
      {
        id: 'vintage-border-inner',
        type: 'shape',
        shape: 'circle',
        x: 70,
        y: 45,
        width: 260,
        height: 160,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: 'none',
        stroke: '#D2691E',
        strokeWidth: 1,
        opacity: 0.6
      },
      // Nome principale
      {
        id: 'trattoria-name',
        type: 'text',
        content: 'NONNA MARIA',
        x: 80,
        y: 90,
        width: 240,
        height: 40,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Merriweather',
        fontSize: 28,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B4513',
        letterSpacing: 2,
        lineHeight: 1.2,
        textDecoration: 'none',
        opacity: 1
      },
      // Sottotitolo
      {
        id: 'trattoria-subtitle',
        type: 'text',
        content: 'Autentica Trattoria Italiana',
        x: 100,
        y: 130,
        width: 200,
        height: 20,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#654321',
        letterSpacing: 1,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.8
      },
      // Decorazione centrale superiore
      {
        id: 'decoration-top',
        type: 'text',
        content: '★',
        x: 190,
        y: 65,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Decorazione centrale inferiore  
      {
        id: 'decoration-bottom',
        type: 'text',
        content: '★ ★ ★',
        x: 170,
        y: 160,
        width: 60,
        height: 15,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 3,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.7
      }
    ]
  },

  {
    id: 'modern-fusion',
    name: 'Modern Fusion',
    category: 'modern',
    preview: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop',
    tags: ['modern', 'fusion', 'geometric', 'minimalist'],
    canvasSize: { width: 450, height: 200 },
    elements: [
      // Elemento geometrico principale
      {
        id: 'geometric-main',
        type: 'shape',
        shape: 'rectangle',
        x: 50,
        y: 70,
        width: 60,
        height: 60,
        rotation: 45,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.9,
        borderRadius: 8
      },
      // Nome del ristorante
      {
        id: 'fusion-name',
        type: 'text',
        content: 'FUSION',
        x: 130,
        y: 75,
        width: 200,
        height: 50,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Montserrat',
        fontSize: 42,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#2C3E50',
        letterSpacing: 4,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Sottotitolo
      {
        id: 'fusion-subtitle',
        type: 'text',
        content: 'Contemporary Cuisine',
        x: 130,
        y: 125,
        width: 250,
        height: 25,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'light',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#7F8C8D',
        letterSpacing: 1,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Elementi geometrici decorativi
      {
        id: 'geo-accent1',
        type: 'shape',
        shape: 'circle',
        x: 350,
        y: 80,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: '#E74C3C',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.8
      },
      {
        id: 'geo-accent2',
        type: 'shape',
        shape: 'circle',
        x: 375,
        y: 100,
        width: 12,
        height: 12,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fill: '#F39C12',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.6
      }
    ]
  },

  {
    id: 'script-artisan',
    name: 'Script Artigianale',
    category: 'elegant',
    preview: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop',
    tags: ['script', 'artisan', 'handmade', 'authentic'],
    canvasSize: { width: 450, height: 180 },
    elements: [
      // Nome principale in script
      {
        id: 'script-main',
        type: 'text',
        content: 'La Bottega',
        x: 75,
        y: 50,
        width: 300,
        height: 80,
        rotation: -3,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Dancing Script',
        fontSize: 56,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B0000',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Sottotitolo elegante
      {
        id: 'script-subtitle',
        type: 'text',
        content: 'del gusto autentico',
        x: 125,
        y: 120,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Cormorant Garamond',
        fontSize: 18,
        fontWeight: 'light',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#2C3E50',
        letterSpacing: 2,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.8
      },
      // Decorazione floreale sinistra
      {
        id: 'flourish-left',
        type: 'text',
        content: '❦',
        x: 50,
        y: 75,
        width: 30,
        height: 30,
        rotation: -15,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 24,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.6
      },
      // Decorazione floreale destra
      {
        id: 'flourish-right',
        type: 'text',
        content: '❦',
        x: 370,
        y: 75,
        width: 30,
        height: 30,
        rotation: 15,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 24,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.6
      }
    ]
  },

  {
    id: 'bistrot-parisien',
    name: 'Bistrot Parigino',
    category: 'vintage',
    preview: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop',
    tags: ['french', 'bistrot', 'vintage', 'classic'],
    canvasSize: { width: 350, height: 280 },
    elements: [
      // Cornice ornamentale
      {
        id: 'ornamental-frame',
        type: 'shape',
        shape: 'rectangle',
        x: 25,
        y: 25,
        width: 300,
        height: 230,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: 'none',
        stroke: '#2C3E50',
        strokeWidth: 3,
        opacity: 1,
        borderRadius: 15
      },
      // Background subtle
      {
        id: 'background-subtle',
        type: 'shape',
        shape: 'rectangle',
        x: 35,
        y: 35,
        width: 280,
        height: 210,
        rotation: 0,
        zIndex: 0,
        locked: false,
        selected: false,
        fill: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
        stroke: 'none',
        strokeWidth: 0,
        opacity: 0.3,
        borderRadius: 10
      },
      // Titolo principale
      {
        id: 'bistrot-title',
        type: 'text',
        content: 'CAFÉ',
        x: 75,
        y: 80,
        width: 200,
        height: 40,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Playfair Display',
        fontSize: 48,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#2C3E50',
        letterSpacing: 8,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Sottotitolo principale
      {
        id: 'bistrot-subtitle',
        type: 'text',
        content: 'LUMIÈRE',
        x: 75,
        y: 125,
        width: 200,
        height: 35,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Playfair Display',
        fontSize: 32,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B4513',
        letterSpacing: 4,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 1
      },
      // Descrizione
      {
        id: 'bistrot-description',
        type: 'text',
        content: 'Bistrot & Brasserie',
        x: 100,
        y: 170,
        width: 150,
        height: 20,
        rotation: 0,
        zIndex: 2,
        locked: false,
        selected: false,
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#34495E',
        letterSpacing: 1,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.8
      },
      // Decorazioni ornamentali
      {
        id: 'ornament-top',
        type: 'text',
        content: '◆',
        x: 165,
        y: 55,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.7
      },
      {
        id: 'ornament-bottom',
        type: 'text',
        content: '◆',
        x: 165,
        y: 200,
        width: 20,
        height: 20,
        rotation: 0,
        zIndex: 1,
        locked: false,
        selected: false,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#DAA520',
        letterSpacing: 0,
        lineHeight: 1,
        textDecoration: 'none',
        opacity: 0.7
      }
    ]
  }
];

import { getAllAwardWinningTemplates } from './AwardWinningTemplates';
import { getAllExtremeTemplates } from './ExtremeDesignTemplates';

// Funzioni specifiche per accedere ai diversi livelli di template
export const getAwardWinningTemplates = getAllAwardWinningTemplates;
export const getExtremeTemplates = getAllExtremeTemplates;