import { LogoTemplate } from './types';

// Template di Logo ESTREMAMENTE Particolari e Award-Winning
// Design innovativi, complessi e di altissimo valore stilistico

export const AWARD_WINNING_TEMPLATES: LogoTemplate[] = [
  // === CATEGORIA: FINE DINING ULTRA LUXURY ===
  {
    id: 'michelin-star-minimalist',
    name: 'Michelin Star Minimalist',
    category: 'elegant',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 400, height: 300 },
    tags: ['luxury', 'minimalist', 'fine-dining', 'award-winning'],
    elements: [
      // Background con gradient sottilissimo
      {
        id: 'bg-gradient',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 400,
        height: 300,
        rotation: 0,
        style: {
          fill: 'linear-gradient(135deg, #fafafa 0%, #f5f5f5 100%)',
          stroke: 'none',
          strokeWidth: 0,
        },
        zIndex: 0,
      },
      // Elemento geometrico ultra-sottile come separatore
      {
        id: 'geometric-line',
        type: 'shape',
        subtype: 'line',
        x: 150,
        y: 120,
        width: 100,
        height: 2,
        rotation: 0,
        style: {
          stroke: '#d4af37',
          strokeWidth: 0.5,
          fill: 'none',
        },
        zIndex: 1,
      },
      // Testo principale con font ultra-elegante
      {
        id: 'main-text',
        type: 'text',
        content: 'AURELIUS',
        x: 200,
        y: 140,
        width: 200,
        height: 40,
        rotation: 0,
        style: {
          fontFamily: 'Playfair Display',
          fontSize: 24,
          fontWeight: '300',
          color: '#1a1a1a',
          textAlign: 'center',
          letterSpacing: '4px',
        },
        zIndex: 2,
      },
      // Sottotitolo con spacing estremo
      {
        id: 'subtitle',
        type: 'text',
        content: 'F I N E  D I N I N G',
        x: 200,
        y: 170,
        width: 200,
        height: 20,
        rotation: 0,
        style: {
          fontFamily: 'Inter',
          fontSize: 8,
          fontWeight: '400',
          color: '#666666',
          textAlign: 'center',
          letterSpacing: '3px',
        },
        zIndex: 2,
      },
      // Elemento decorativo minimalista
      {
        id: 'decorative-dot',
        type: 'shape',
        subtype: 'circle',
        x: 198,
        y: 108,
        width: 4,
        height: 4,
        rotation: 0,
        style: {
          fill: '#d4af37',
          stroke: 'none',
        },
        zIndex: 1,
      },
    ],
  },

  // === CATEGORIA: AVANT-GARDE EXPERIMENTAL ===
  {
    id: 'deconstructed-typography',
    name: 'Deconstructed Typography',
    category: 'modern',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 500, height: 400 },
    tags: ['avant-garde', 'experimental', 'typography', 'artistic'],
    elements: [
      // Background nero drammatico
      {
        id: 'dramatic-bg',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 500,
        height: 400,
        rotation: 0,
        style: {
          fill: '#0a0a0a',
          stroke: 'none',
        },
        zIndex: 0,
      },
      // Lettera "R" decostruita - parte 1
      {
        id: 'letter-r-part1',
        type: 'shape',
        subtype: 'rectangle',
        x: 150,
        y: 100,
        width: 8,
        height: 120,
        rotation: 0,
        style: {
          fill: '#ff4444',
          stroke: 'none',
        },
        zIndex: 2,
      },
      // Lettera "R" decostruita - parte 2 (curva superiore)
      {
        id: 'letter-r-part2',
        type: 'shape',
        subtype: 'path',
        x: 158,
        y: 100,
        width: 40,
        height: 40,
        rotation: 0,
        style: {
          fill: 'none',
          stroke: '#ff4444',
          strokeWidth: 8,
          pathData: 'M 0 0 Q 40 0 40 20 Q 40 40 0 40',
        },
        zIndex: 2,
      },
      // Lettera "R" decostruita - gamba diagonale
      {
        id: 'letter-r-part3',
        type: 'shape',
        subtype: 'rectangle',
        x: 170,
        y: 150,
        width: 50,
        height: 8,
        rotation: 35,
        style: {
          fill: '#ff4444',
          stroke: 'none',
        },
        zIndex: 2,
      },
      // Particelle che "volano via" dalla lettera
      {
        id: 'particle-1',
        type: 'shape',
        subtype: 'rectangle',
        x: 220,
        y: 120,
        width: 3,
        height: 3,
        rotation: 45,
        style: {
          fill: '#ff6666',
          stroke: 'none',
        },
        zIndex: 1,
      },
      {
        id: 'particle-2',
        type: 'shape',
        subtype: 'rectangle',
        x: 240,
        y: 110,
        width: 2,
        height: 2,
        rotation: 30,
        style: {
          fill: '#ff8888',
          stroke: 'none',
        },
        zIndex: 1,
      },
      {
        id: 'particle-3',
        type: 'shape',
        subtype: 'rectangle',
        x: 260,
        y: 105,
        width: 1,
        height: 1,
        rotation: 60,
        style: {
          fill: '#ffaaaa',
          stroke: 'none',
        },
        zIndex: 1,
      },
      // Testo complementare ultra-moderno
      {
        id: 'restaurant-name',
        type: 'text',
        content: 'RIOT KITCHEN',
        x: 150,
        y: 280,
        width: 200,
        height: 30,
        rotation: 0,
        style: {
          fontFamily: 'Roboto Mono',
          fontSize: 16,
          fontWeight: '700',
          color: '#ffffff',
          textAlign: 'left',
          letterSpacing: '2px',
        },
        zIndex: 2,
      },
    ],
  },

  // === CATEGORIA: LUXURY WINE BAR ===
  {
    id: 'wine-calligraphy-masterpiece',
    name: 'Wine Calligraphy Masterpiece',
    category: 'wine-bar',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 450, height: 350 },
    tags: ['luxury', 'wine', 'calligraphy', 'sophisticated'],
    elements: [
      // Background con texture carta pergamena
      {
        id: 'parchment-bg',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 450,
        height: 350,
        rotation: 0,
        style: {
          fill: 'linear-gradient(45deg, #faf9f6 0%, #f5f4f0 25%, #faf9f6 50%, #f0efe8 75%, #faf9f6 100%)',
          stroke: 'none',
        },
        zIndex: 0,
      },
      // Stemma con forma di scudo
      {
        id: 'wine-crest',
        type: 'shape',
        subtype: 'path',
        x: 200,
        y: 80,
        width: 50,
        height: 60,
        rotation: 0,
        style: {
          fill: 'none',
          stroke: '#722f37',
          strokeWidth: 2,
          pathData: 'M 25 0 L 50 15 L 50 45 Q 50 60 25 60 Q 0 60 0 45 L 0 15 Z',
        },
        zIndex: 2,
      },
      // Grappolo d'uva stilizzato dentro lo stemma
      {
        id: 'grape-cluster',
        type: 'shape',
        subtype: 'circle',
        x: 220,
        y: 100,
        width: 4,
        height: 4,
        rotation: 0,
        style: {
          fill: '#722f37',
          stroke: 'none',
        },
        zIndex: 3,
      },
      {
        id: 'grape-2',
        type: 'shape',
        subtype: 'circle',
        x: 218,
        y: 105,
        width: 3,
        height: 3,
        rotation: 0,
        style: {
          fill: '#722f37',
          stroke: 'none',
        },
        zIndex: 3,
      },
      {
        id: 'grape-3',
        type: 'shape',
        subtype: 'circle',
        x: 224,
        y: 105,
        width: 3,
        height: 3,
        rotation: 0,
        style: {
          fill: '#722f37',
          stroke: 'none',
        },
        zIndex: 3,
      },
      // Testo principale con calligrafia elegante
      {
        id: 'wine-name',
        type: 'text',
        content: 'Château Lumière',
        x: 225,
        y: 180,
        width: 300,
        height: 50,
        rotation: 0,
        style: {
          fontFamily: 'Dancing Script',
          fontSize: 36,
          fontWeight: '600',
          color: '#722f37',
          textAlign: 'center',
          letterSpacing: '1px',
        },
        zIndex: 2,
      },
      // Linee decorative ornamentali
      {
        id: 'ornament-left',
        type: 'shape',
        subtype: 'path',
        x: 120,
        y: 200,
        width: 80,
        height: 20,
        rotation: 0,
        style: {
          fill: 'none',
          stroke: '#d4af37',
          strokeWidth: 1,
          pathData: 'M 0 10 Q 20 0 40 10 Q 60 20 80 10',
        },
        zIndex: 1,
      },
      {
        id: 'ornament-right',
        type: 'shape',
        subtype: 'path',
        x: 250,
        y: 200,
        width: 80,
        height: 20,
        rotation: 0,
        style: {
          fill: 'none',
          stroke: '#d4af37',
          strokeWidth: 1,
          pathData: 'M 0 10 Q 20 20 40 10 Q 60 0 80 10',
        },
        zIndex: 1,
      },
      // Anno di fondazione
      {
        id: 'established-year',
        type: 'text',
        content: 'EST. MMXV',
        x: 225,
        y: 240,
        width: 150,
        height: 20,
        rotation: 0,
        style: {
          fontFamily: 'Cinzel',
          fontSize: 12,
          fontWeight: '400',
          color: '#8b7355',
          textAlign: 'center',
          letterSpacing: '2px',
        },
        zIndex: 2,
      },
    ],
  },

  // === CATEGORIA: FUTURISTIC MOLECULAR GASTRONOMY ===
  {
    id: 'molecular-geometry',
    name: 'Molecular Geometry',
    category: 'modern',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 600, height: 400 },
    tags: ['futuristic', 'molecular', 'geometry', 'innovative'],
    elements: [
      // Background con gradient cosmico
      {
        id: 'cosmic-bg',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 600,
        height: 400,
        rotation: 0,
        style: {
          fill: 'radial-gradient(circle at 30% 40%, #1a1a2e 0%, #16213e 25%, #0f3460 50%, #533483 100%)',
          stroke: 'none',
        },
        zIndex: 0,
      },
      // Struttura molecolare centrale
      {
        id: 'molecule-center',
        type: 'shape',
        subtype: 'circle',
        x: 290,
        y: 190,
        width: 20,
        height: 20,
        rotation: 0,
        style: {
          fill: '#00d4ff',
          stroke: '#ffffff',
          strokeWidth: 2,
        },
        zIndex: 3,
      },
      // Atomi satelliti
      {
        id: 'atom-1',
        type: 'shape',
        subtype: 'circle',
        x: 340,
        y: 160,
        width: 12,
        height: 12,
        rotation: 0,
        style: {
          fill: '#ff6b6b',
          stroke: '#ffffff',
          strokeWidth: 1,
        },
        zIndex: 2,
      },
      {
        id: 'atom-2',
        type: 'shape',
        subtype: 'circle',
        x: 250,
        y: 140,
        width: 12,
        height: 12,
        rotation: 0,
        style: {
          fill: '#4ecdc4',
          stroke: '#ffffff',
          strokeWidth: 1,
        },
        zIndex: 2,
      },
      {
        id: 'atom-3',
        type: 'shape',
        subtype: 'circle',
        x: 330,
        y: 230,
        width: 12,
        height: 12,
        rotation: 0,
        style: {
          fill: '#ffe66d',
          stroke: '#ffffff',
          strokeWidth: 1,
        },
        zIndex: 2,
      },
      // Collegamenti molecolari
      {
        id: 'bond-1',
        type: 'shape',
        subtype: 'line',
        x: 300,
        y: 200,
        width: 46,
        height: 2,
        rotation: -20,
        style: {
          stroke: '#ffffff',
          strokeWidth: 1,
          fill: 'none',
        },
        zIndex: 1,
      },
      {
        id: 'bond-2',
        type: 'shape',
        subtype: 'line',
        x: 290,
        y: 190,
        width: 46,
        height: 2,
        rotation: 45,
        style: {
          stroke: '#ffffff',
          strokeWidth: 1,
          fill: 'none',
        },
        zIndex: 1,
      },
      {
        id: 'bond-3',
        type: 'shape',
        subtype: 'line',
        x: 300,
        y: 200,
        width: 42,
        height: 2,
        rotation: -45,
        style: {
          stroke: '#ffffff',
          strokeWidth: 1,
          fill: 'none',
        },
        zIndex: 1,
      },
      // Nome del ristorante futuristico
      {
        id: 'future-name',
        type: 'text',
        content: 'QUANTUM',
        x: 300,
        y: 290,
        width: 200,
        height: 40,
        rotation: 0,
        style: {
          fontFamily: 'Orbitron',
          fontSize: 28,
          fontWeight: '700',
          color: '#00d4ff',
          textAlign: 'center',
          letterSpacing: '4px',
          textShadow: '0 0 10px #00d4ff',
        },
        zIndex: 3,
      },
      // Sottotitolo con effetto glow
      {
        id: 'molecular-subtitle',
        type: 'text',
        content: 'MOLECULAR GASTRONOMY',
        x: 300,
        y: 320,
        width: 250,
        height: 20,
        rotation: 0,
        style: {
          fontFamily: 'Exo 2',
          fontSize: 10,
          fontWeight: '300',
          color: '#ffffff',
          textAlign: 'center',
          letterSpacing: '2px',
          opacity: 0.8,
        },
        zIndex: 3,
      },
    ],
  },

  // === CATEGORIA: ARTISANAL COFFEE CULTURE ===
  {
    id: 'coffee-bean-mandala',
    name: 'Coffee Bean Mandala',
    category: 'modern',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 400, height: 400 },
    tags: ['artisanal', 'coffee', 'mandala', 'cultural'],
    elements: [
      // Background color caldo
      {
        id: 'warm-bg',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 400,
        height: 400,
        rotation: 0,
        style: {
          fill: '#f7f3e9',
          stroke: 'none',
        },
        zIndex: 0,
      },
      // Centro del mandala - chicco di caffè stilizzato
      {
        id: 'coffee-bean-center',
        type: 'shape',
        subtype: 'ellipse',
        x: 190,
        y: 190,
        width: 20,
        height: 30,
        rotation: 0,
        style: {
          fill: '#8b4513',
          stroke: 'none',
        },
        zIndex: 2,
      },
      // Linea centrale del chicco
      {
        id: 'bean-line',
        type: 'shape',
        subtype: 'path',
        x: 200,
        y: 190,
        width: 2,
        height: 20,
        rotation: 0,
        style: {
          stroke: '#654321',
          strokeWidth: 2,
          fill: 'none',
          pathData: 'M 0 0 Q 1 10 0 20',
        },
        zIndex: 3,
      },
      // Primo anello di chicchi (8 chicchi)
      {
        id: 'bean-ring-1-1',
        type: 'shape',
        subtype: 'ellipse',
        x: 190,
        y: 150,
        width: 12,
        height: 18,
        rotation: 0,
        style: {
          fill: '#a0522d',
          stroke: 'none',
        },
        zIndex: 2,
      },
      {
        id: 'bean-ring-1-2',
        type: 'shape',
        subtype: 'ellipse',
        x: 220,
        y: 165,
        width: 12,
        height: 18,
        rotation: 45,
        style: {
          fill: '#a0522d',
          stroke: 'none',
        },
        zIndex: 2,
      },
      {
        id: 'bean-ring-1-3',
        type: 'shape',
        subtype: 'ellipse',
        x: 235,
        y: 195,
        width: 12,
        height: 18,
        rotation: 90,
        style: {
          fill: '#a0522d',
          stroke: 'none',
        },
        zIndex: 2,
      },
      {
        id: 'bean-ring-1-4',
        type: 'shape',
        subtype: 'ellipse',
        x: 220,
        y: 225,
        width: 12,
        height: 18,
        rotation: 135,
        style: {
          fill: '#a0522d',
          stroke: 'none',
        },
        zIndex: 2,
      },
      // Testo con font artigianale
      {
        id: 'coffee-name',
        type: 'text',
        content: 'BEAN RITUAL',
        x: 200,
        y: 320,
        width: 200,
        height: 30,
        rotation: 0,
        style: {
          fontFamily: 'Merriweather',
          fontSize: 18,
          fontWeight: '700',
          color: '#3e2723',
          textAlign: 'center',
          letterSpacing: '2px',
        },
        zIndex: 3,
      },
      // Cerchio esterno decorativo
      {
        id: 'outer-circle',
        type: 'shape',
        subtype: 'circle',
        x: 120,
        y: 120,
        width: 160,
        height: 160,
        rotation: 0,
        style: {
          fill: 'none',
          stroke: '#d7ccc8',
          strokeWidth: 1,
          strokeDasharray: '5,5',
        },
        zIndex: 1,
      },
    ],
  },

  // === CATEGORIA: PREMIUM STEAKHOUSE ===
  {
    id: 'fire-and-steel',
    name: 'Fire & Steel',
    category: 'restaurant',
    preview: 'data:image/svg+xml;base64,...',
    canvasSize: { width: 500, height: 300 },
    tags: ['steakhouse', 'premium', 'fire', 'masculine'],
    elements: [
      // Background nero con texture
      {
        id: 'steel-bg',
        type: 'shape',
        subtype: 'rectangle',
        x: 0,
        y: 0,
        width: 500,
        height: 300,
        rotation: 0,
        style: {
          fill: 'linear-gradient(45deg, #1a1a1a 0%, #2d2d2d 25%, #1a1a1a 50%, #2d2d2d 75%, #1a1a1a 100%)',
          stroke: 'none',
        },
        zIndex: 0,
      },
      // Forma di bistecca stilizzata
      {
        id: 'steak-shape',
        type: 'shape',
        subtype: 'path',
        x: 200,
        y: 100,
        width: 100,
        height: 60,
        rotation: 0,
        style: {
          fill: '#8b4513',
          stroke: '#654321',
          strokeWidth: 2,
          pathData: 'M 0 30 Q 10 0 30 10 Q 50 0 70 15 Q 90 5 100 25 Q 90 40 80 50 Q 60 60 40 55 Q 20 60 10 45 Q 0 40 0 30',
        },
        zIndex: 2,
      },
      // Effetti di fuoco/calore
      {
        id: 'flame-1',
        type: 'shape',
        subtype: 'path',
        x: 220,
        y: 80,
        width: 15,
        height: 25,
        rotation: 0,
        style: {
          fill: '#ff4500',
          stroke: 'none',
          pathData: 'M 7 25 Q 0 15 3 10 Q 2 5 7 0 Q 12 5 11 10 Q 15 15 7 25',
        },
        zIndex: 3,
      },
      {
        id: 'flame-2',
        type: 'shape',
        subtype: 'path',
        x: 240,
        y: 85,
        width: 12,
        height: 20,
        rotation: 0,
        style: {
          fill: '#ff6600',
          stroke: 'none',
          pathData: 'M 6 20 Q 0 12 2 8 Q 1 4 6 0 Q 10 4 9 8 Q 12 12 6 20',
        },
        zIndex: 3,
      },
      {
        id: 'flame-3',
        type: 'shape',
        subtype: 'path',
        x: 260,
        y: 82,
        width: 10,
        height: 18,
        rotation: 0,
        style: {
          fill: '#ff8800',
          stroke: 'none',
          pathData: 'M 5 18 Q 0 10 2 6 Q 1 3 5 0 Q 8 3 7 6 Q 10 10 5 18',
        },
        zIndex: 3,
      },
      // Nome del ristorante con font robusto
      {
        id: 'steakhouse-name',
        type: 'text',
        content: 'IRON FORGE',
        x: 250,
        y: 210,
        width: 300,
        height: 40,
        rotation: 0,
        style: {
          fontFamily: 'Bebas Neue',
          fontSize: 32,
          fontWeight: '900',
          color: '#ff4500',
          textAlign: 'center',
          letterSpacing: '3px',
          textShadow: '2px 2px 4px rgba(0,0,0,0.8)',
        },
        zIndex: 3,
      },
      // Sottotitolo
      {
        id: 'steakhouse-subtitle',
        type: 'text',
        content: 'PREMIUM STEAKHOUSE',
        x: 250,
        y: 240,
        width: 250,
        height: 20,
        rotation: 0,
        style: {
          fontFamily: 'Oswald',
          fontSize: 12,
          fontWeight: '400',
          color: '#cccccc',
          textAlign: 'center',
          letterSpacing: '2px',
        },
        zIndex: 3,
      },
      // Linee decorative in stile industriale
      {
        id: 'industrial-line-1',
        type: 'shape',
        subtype: 'rectangle',
        x: 150,
        y: 195,
        width: 80,
        height: 2,
        rotation: 0,
        style: {
          fill: '#666666',
          stroke: 'none',
        },
        zIndex: 1,
      },
      {
        id: 'industrial-line-2',
        type: 'shape',
        subtype: 'rectangle',
        x: 270,
        y: 195,
        width: 80,
        height: 2,
        rotation: 0,
        style: {
          fill: '#666666',
          stroke: 'none',
        },
        zIndex: 1,
      },
    ],
  },
];

// Funzione per ottenere tutti i template award-winning
export const getAllAwardWinningTemplates = () => AWARD_WINNING_TEMPLATES;